/* * ======================================================================================
 * INVENTORY MANAGEMENT SYSTEM SCHEMA
 * ======================================================================================
 * This schema handles multi-tenant inventory management.
 * - Users: The business owners using the app.
 * - Customers/Suppliers: Entities related to a specific User.
 * - Products: Inventory items owned by the User.
 * - Orders: Inbound transactions (Buying stock from Suppliers).
 * - Sales: Outbound transactions (Selling stock to Customers).
 * ======================================================================================
 */
-- 1. USERS
-- Stores the application users (Business Owners).
-- Linked directly to Supabase Authentication.
CREATE TABLE
    public.users (
        id uuid REFERENCES auth.users NOT NULL PRIMARY KEY, -- Links to Supabase Auth ID
        email text,
        name text, -- Display name of the business owner
        profile_picture text, -- URL to the image storage
        created_at timestamp
        with
            time zone DEFAULT now (),
            updated_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 2. CUSTOMERS
-- The clients/buyers of the Business Owner.
CREATE TABLE
    public.customers (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        contact_number text,
        address text, -- Shipping or billing address
        user_id uuid REFERENCES public.users (id), -- The business owner who owns this customer data
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 3. SUPPLIERS
-- The vendors/distributors from whom the Business Owner buys products.
CREATE TABLE
    public.suppliers (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_name text NOT NULL,
        contact_number text,
        address text,
        purchase_link text, -- E.g., Link to Tokopedia/Shopee/Website
        user_id uuid REFERENCES public.users (id),
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 4. PRODUCTS
-- The main inventory catalog.
CREATE TABLE
    public.products (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_name text NOT NULL,
        product_type text, -- E.g., 'Electronics', 'Clothing'
        product_category text, -- E.g., 'Smartphone', 'T-Shirt'
        amount_stock integer DEFAULT 0 NOT NULL, -- Current quantity on hand
        buy_price numeric(15, 2) DEFAULT 0.00 NOT NULL, -- Cost of Goods Sold (COGS) reference
        sell_price numeric(15, 2) DEFAULT 0.00 NOT NULL, -- Selling price reference
        product_image text, -- URL to image storage
        supplier_id bigint REFERENCES public.suppliers (id) ON DELETE SET NULL, -- Default supplier for this item
        user_id uuid REFERENCES public.users (id),
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 5. ORDER SEQUENCES 
-- Helper table to generate readable Purchase Order codes (e.g., PO-202310-001).
-- It tracks the last number used for a specific month/year key.
CREATE TABLE
    public.order_sequences (
        date_key text NOT NULL PRIMARY KEY, -- Format: YYYYMM (e.g., '202310')
        last_number bigint DEFAULT 0 -- Increments for every new order in that month
    );

-- 6. INVOICE SEQUENCES 
-- Helper table to generate readable Invoice codes (e.g., INV-202310-001).
CREATE TABLE
    public.invoice_sequences (
        date_key text NOT NULL PRIMARY KEY, -- Format: YYYYMM
        last_number bigint DEFAULT 0
    );

-- --------------------------------------------------------------------------------------
-- 7. ORDERS (PURCHASE ORDERS)
-- Represents Inbound Transactions (Restocking items from Suppliers).
CREATE TABLE
    public.orders (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        po_code text UNIQUE, -- Human-readable code (e.g., PO-202310-001)
        status text NOT NULL DEFAULT 'Pending', -- Enum: 'Pending', 'Shipped', 'Completed', 'Cancelled'
        total_cost numeric(15, 2) DEFAULT 0.00, -- Total value of the purchase
        expected_delivery_date timestamp without time zone,
        supplier_id bigint REFERENCES public.suppliers (id) ON DELETE SET NULL,
        user_id uuid REFERENCES public.users (id),
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- 8. ORDER ITEMS
-- The specific products and quantities within a Purchase Order.
CREATE TABLE
    public.order_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id bigint REFERENCES public.orders (id) ON DELETE CASCADE NOT NULL, -- If Order is deleted, items are deleted
        product_id bigint REFERENCES public.products (id) ON DELETE RESTRICT NOT NULL, -- Cannot delete Product if it exists in an order
        quantity integer NOT NULL, -- Number of items ordered
        cost_per_item numeric(15, 2) NOT NULL, -- Historical cost at the time of purchase
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 9. SALES (INVOICES)
-- Represents Outbound Transactions (Selling items to Customers).
CREATE TABLE
    public.sales (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        invoice_code text UNIQUE, -- Human-readable code (e.g., INV-202310-001)
        sale_date timestamp
        with
            time zone DEFAULT now (),
            total_amount numeric(15, 2) DEFAULT 0.00, -- Total revenue from this sale
            payment_method text, -- E.g., 'Cash', 'Transfer', 'QRIS'
            payment_status text DEFAULT 'Paid', -- Enum: 'Paid', 'Unpaid', 'Partial'
            notes text, -- Optional notes for the invoice
            customer_id bigint REFERENCES public.customers (id) ON DELETE SET NULL,
            user_id uuid REFERENCES public.users (id) NOT NULL
    );

-- 10. SALES ITEMS
-- The specific products and quantities within a Sale.
CREATE TABLE
    public.sales_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sales_id bigint REFERENCES public.sales (id) ON DELETE CASCADE NOT NULL,
        product_id bigint REFERENCES public.products (id) ON DELETE RESTRICT NOT NULL,
        quantity integer NOT NULL, -- Number of items sold
        price_at_sale numeric(15, 2) NOT NULL, -- Selling price at that moment (Revenue)
        cost_at_sale numeric(15, 2) DEFAULT 0, -- Buy price at that moment (for Profit/Loss calculation)
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- ======================================================================================
-- SECURITY: ROW LEVEL SECURITY (RLS) POLICIES
-- ======================================================================================
-- Enable RLS for all tables to prevent public access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_items ENABLE ROW LEVEL SECURITY;

-- 1. USERS
-- Users can only read and manage their own profile
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.users FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can delete own profile" ON public.users FOR DELETE USING (auth.uid() = id);

-- 2. CUSTOMERS
CREATE POLICY "Users manage own customers" ON public.customers FOR ALL USING (auth.uid() = user_id);

-- 3. SUPPLIERS
CREATE POLICY "Users manage own suppliers" ON public.suppliers FOR ALL USING (auth.uid() = user_id);

-- 4. PRODUCTS
CREATE POLICY "Users manage own products" ON public.products FOR ALL USING (auth.uid() = user_id);

-- 5. ORDER SEQUENCES
-- Global sequences, allowing any authenticated user to process orders
CREATE POLICY "Authenticated users can access order sequences" ON public.order_sequences FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. INVOICE SEQUENCES
-- Global sequences, allowing any authenticated user to process invoices
CREATE POLICY "Authenticated users can access invoice sequences" ON public.invoice_sequences FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 7. ORDERS
CREATE POLICY "Users manage own orders" ON public.orders FOR ALL USING (auth.uid() = user_id);

-- 8. ORDER ITEMS
-- Uses EXISTS to check if the related order belongs to the user
CREATE POLICY "Users manage own order items" ON public.order_items FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.orders o
    WHERE o.id = order_items.order_id AND o.user_id = auth.uid()
  )
);

-- 9. SALES
CREATE POLICY "Users manage own sales" ON public.sales FOR ALL USING (auth.uid() = user_id);

-- 10. SALES ITEMS
-- Uses EXISTS to check if the related sale belongs to the user
CREATE POLICY "Users manage own sales items" ON public.sales_items FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.sales s
    WHERE s.id = sales_items.sales_id AND s.user_id = auth.uid()
  )
);