-- ============================================================
-- SUPPLIER FINANCE & RESERVATION MIGRATION
-- Run this once in your Supabase SQL Editor
-- ============================================================

-- 1. Add new columns to the suppliers table
ALTER TABLE public.suppliers
ADD COLUMN IF NOT EXISTS reserved_space_m3 numeric(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS reservation_cost numeric(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS reservation_period text DEFAULT 'Monthly', -- 'Weekly', 'Monthly', 'Yearly'
ADD COLUMN IF NOT EXISTS next_deduction_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS has_insufficient_funds boolean DEFAULT false;

-- 2. Create the supplier_transactions table
CREATE TABLE IF NOT EXISTS public.supplier_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id bigint REFERENCES public.suppliers(id) ON DELETE CASCADE NOT NULL,
    transaction_type text NOT NULL CHECK (transaction_type IN ('CREDIT', 'CHARGE')),
    amount numeric(15,2) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Enable RLS on supplier_transactions
ALTER TABLE public.supplier_transactions ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies for supplier_transactions
-- Admin/User (business owner) can manage transactions for their own suppliers
CREATE POLICY "Users manage transactions of their suppliers" ON public.supplier_transactions
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.suppliers s
    WHERE s.id = supplier_transactions.supplier_id AND s.user_id = auth.uid()
  )
);

-- Supplier Portal users can view their own transactions
CREATE POLICY "Portal users view their own transactions" ON public.supplier_transactions
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.suppliers s
    WHERE s.id = supplier_transactions.supplier_id AND s.portal_user_id = auth.uid()
  )
);

-- 5. Create a view to easily calculate the current balance for a supplier
-- Balance = SUM(CREDIT) - SUM(CHARGE)
CREATE OR REPLACE VIEW public.supplier_balances AS
SELECT 
    supplier_id,
    COALESCE(SUM(CASE WHEN transaction_type = 'CREDIT' THEN amount ELSE 0 END), 0) - 
    COALESCE(SUM(CASE WHEN transaction_type = 'CHARGE' THEN amount ELSE 0 END), 0) as balance
FROM public.supplier_transactions
GROUP BY supplier_id;

-- Ensure the view is accessible
GRANT SELECT ON public.supplier_balances TO authenticated;
GRANT SELECT ON public.supplier_balances TO anon;
